<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ResCountry as Country;
use App\Models\ResCurrency as Currency;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->CreateCountry();
    }

    public function CreateCountry()
    {
        $country_data = $this->CountryData();
        foreach ($country_data as $country) {
            Country::create($country);
        }
    }

    public function CountryData()
    {
        $country= [
            [
                "name"=>"Andorra",
                "code"=>"ad",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"376",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),         ],
            [
                "name"=>"United Arab Emirates",
                "code"=>"ae",
                "currency_id"=>Currency::where("name","AED")->first()->id,
                "phone_code"=>"971",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Afghanistan",
                "code"=>"af",
                "currency_id"=>Currency::where("name","AFN")->first()->id,
                "phone_code"=>"93",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Antigua and Barbuda",
                "code"=>"ag",
                "currency_id"=>Currency::where("name","XCD")->first()->id,
                "phone_code"=>"1268",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Anguilla",
                "code"=>"ai",
                "currency_id"=>Currency::where("name","XCD")->first()->id,
                "phone_code"=>"1264",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Albania",
                "code"=>"al",
                "currency_id"=>Currency::where("name","ALL")->first()->id,
                "phone_code"=>"355",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Armenia",
                "code"=>"am",
                "currency_id"=>Currency::where("name","AMD")->first()->id,
                "phone_code"=>"374",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Angola",
                "code"=>"ao",
                "currency_id"=>Currency::where("name","AOA")->first()->id,
                "phone_code"=>"244",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Antarctica",
                "code"=>"aq",
                "currency_id"=>Currency::where("name","XCD")->first()->id,
                "phone_code"=>"672",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Argentina",
                "code"=>"ar",
                "currency_id"=>Currency::where("name","ARS")->first()->id,
                "phone_code"=>"54",
                "vat_label"=>"CUIT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"American Samoa",
                "code"=>"as",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"1684",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Austria",
                "code"=>"at",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"43",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Australia",
                "code"=>"au",
                "currency_id"=>Currency::where("name","AUD")->first()->id,
                "phone_code"=>"61",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Aruba",
                "code"=>"aw",
                "currency_id"=>Currency::where("name","AWG")->first()->id,
                "phone_code"=>"297",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Åland Islands",
                "code"=>"ax",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"358",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Azerbaijan",
                "code"=>"az",
                "currency_id"=>Currency::where("name","AZN")->first()->id,
                "phone_code"=>"994",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Bosnia and Herzegovina",
                "code"=>"ba",
                "currency_id"=>Currency::where("name","BAM")->first()->id,
                "phone_code"=>"387",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Barbados",
                "code"=>"bb",
                "currency_id"=>Currency::where("name","BBD")->first()->id,
                "phone_code"=>"1246",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Bangladesh",
                "code"=>"bd",
                "currency_id"=>Currency::where("name","BDT")->first()->id,
                "phone_code"=>"880",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Belgium",
                "code"=>"be",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"32",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Burkina Faso",
                "code"=>"bf",
                "currency_id"=>Currency::where("name","XOF")->first()->id,
                "phone_code"=>"226",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Bulgaria",
                "code"=>"bg",
                "currency_id"=>Currency::where("name","BGN")->first()->id,
                "phone_code"=>"359",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Bahrain",
                "code"=>"bh",
                "currency_id"=>Currency::where("name","BHD")->first()->id,
                "phone_code"=>"973",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Burundi",
                "code"=>"bi",
                "currency_id"=>Currency::where("name","BIF")->first()->id,
                "phone_code"=>"257",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Benin",
                "code"=>"bj",
                "currency_id"=>Currency::where("name","XOF")->first()->id,
                "phone_code"=>"229",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Saint Barthélémy",
                "code"=>"bl",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"590",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Bermuda",
                "code"=>"bm",
                "currency_id"=>Currency::where("name","BMD")->first()->id,
                "phone_code"=>"1441",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Brunei Darussalam",
                "code"=>"bn",
                "currency_id"=>Currency::where("name","BND")->first()->id,
                "phone_code"=>"673",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Bolivia",
                "code"=>"bo",
                "currency_id"=>Currency::where("name","BOB")->first()->id,
                "phone_code"=>"591",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Bonaire, Sint Eustatius and Saba",
                "code"=>"bq",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"599",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Brazil",
                "code"=>"br",
                "currency_id"=>Currency::where("name","BRL")->first()->id,
                "phone_code"=>"55",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Bahamas",
                "code"=>"bs",
                "currency_id"=>Currency::where("name","BSD")->first()->id,
                "phone_code"=>"1242",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Bhutan",
                "code"=>"bt",
                "currency_id"=>Currency::where("name","BTN")->first()->id,
                "phone_code"=>"975",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Bouvet Island",
                "code"=>"bv",
                "currency_id"=>Currency::where("name","NOK")->first()->id,
                "phone_code"=>"55",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Botswana",
                "code"=>"bw",
                "currency_id"=>Currency::where("name","BWP")->first()->id,
                "phone_code"=>"267",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Belarus",
                "code"=>"by",
                "currency_id"=>Currency::where("name","BYN")->first()->id,
                "phone_code"=>"375",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Belize",
                "code"=>"bz",
                "currency_id"=>Currency::where("name","BZD")->first()->id,
                "phone_code"=>"501",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Canada",
                "code"=>"ca",
                "currency_id"=>Currency::where("name","CAD")->first()->id,
                "phone_code"=>"1",
                "vat_label"=>"HST",            
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Cocos (Keeling) Islands",
                "code"=>"cc",
                "currency_id"=>Currency::where("name","AUD")->first()->id,
                "phone_code"=>"61",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Central African Republic",
                "code"=>"cf",
                "currency_id"=>Currency::where("name","XAF")->first()->id,
                "phone_code"=>"236",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Democratic Republic of the Congo",
                "code"=>"cd",
                "currency_id"=>Currency::where("name","CDF")->first()->id,
                "phone_code"=>"242",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Congo",
                "code"=>"cg",
                "currency_id"=>Currency::where("name","XAF")->first()->id,
                "phone_code"=>"243",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Switzerland",
                "code"=>"ch",
                "currency_id"=>Currency::where("name","CHF")->first()->id,
                "phone_code"=>"41",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Côte d'Ivoire",
                "code"=>"ci",
                "currency_id"=>Currency::where("name","XOF")->first()->id,
                "phone_code"=>"225",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Cook Islands",
                "code"=>"ck",
                "currency_id"=>Currency::where("name","NZD")->first()->id,
                "phone_code"=>"682",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Chile",
                "code"=>"cl",
                "currency_id"=>Currency::where("name","CLP")->first()->id,
                "phone_code"=>"56",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Cameroon",
                "code"=>"cm",
                "currency_id"=>Currency::where("name","XAF")->first()->id,
                "phone_code"=>"237",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"China",
                "code"=>"cn",
                "currency_id"=>Currency::where("name","CNY")->first()->id,
                "phone_code"=>"86",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Colombia",
                "code"=>"co",
                "vat_label"=>"NIT",
                "currency_id"=>Currency::where("name","COP")->first()->id,
                "phone_code"=>"57",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Costa Rica",
                "code"=>"cr",
                "currency_id"=>Currency::where("name","CRC")->first()->id,
                "phone_code"=>"506",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Cuba",
                "code"=>"cu",
                "currency_id"=>Currency::where("name","CUP")->first()->id,
                "phone_code"=>"53",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Cape Verde",
                "code"=>"cv",
                "currency_id"=>Currency::where("name","CVE")->first()->id,
                "phone_code"=>"238",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Curaçao",
                "code"=>"cw",
                "currency_id"=>Currency::where("name","ANG")->first()->id,
                "phone_code"=>"599",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Christmas Island",
                "code"=>"cx",
                "currency_id"=>Currency::where("name","AUD")->first()->id,
                "phone_code"=>"61",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Cyprus",
                "code"=>"cy",
                "currency_id"=>Currency::where("name","CYP")->first()->id,
                "phone_code"=>"357",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Czech Republic",
                "code"=>"cz",
                "currency_id"=>Currency::where("name","CZK")->first()->id,
                "phone_code"=>"420",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Germany",
                "code"=>"de",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"49",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Djibouti",
                "code"=>"dj",
                "currency_id"=>Currency::where("name","DJF")->first()->id,
                "phone_code"=>"253",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Denmark",
                "code"=>"dk",
                "currency_id"=>Currency::where("name","DKK")->first()->id,
                "phone_code"=>"45",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Dominica",
                "code"=>"dm",
                "currency_id"=>Currency::where("name","XCD")->first()->id,
                "phone_code"=>"1767",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Dominican Republic",
                "code"=>"do",
                "currency_id"=>Currency::where("name","DOP")->first()->id,
                "phone_code"=>"1849",
                "vat_label"=>"RNC",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Algeria",
                "code"=>"dz",
                "currency_id"=>Currency::where("name","DZD")->first()->id,
                "phone_code"=>"213",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Ecuador",
                "code"=>"ec",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"593",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Estonia",
                "code"=>"ee",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"372",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Egypt",
                "code"=>"eg",
                "currency_id"=>Currency::where("name","EGP")->first()->id,
                "phone_code"=>"20",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Western Sahara",
                "code"=>"eh",
                "currency_id"=>Currency::where("name","MAD")->first()->id,
                "phone_code"=>"212",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Eritrea",
                "code"=>"er",
                "currency_id"=>Currency::where("name","ERN")->first()->id,
                "phone_code"=>"291",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Spain",
                "code"=>"es",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"34",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Ethiopia",
                "code"=>"et",
                "currency_id"=>Currency::where("name","ETB")->first()->id,
                "phone_code"=>"251",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Finland",
                "code"=>"fi",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"358",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Fiji",
                "code"=>"fj",
                "currency_id"=>Currency::where("name","FJD")->first()->id,
                "phone_code"=>"679",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Falkland Islands",
                "code"=>"fk",
                "currency_id"=>Currency::where("name","FKP")->first()->id,
                "phone_code"=>"500",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Micronesia",
                "code"=>"fm",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"691",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Faroe Islands",
                "code"=>"fo",
                "currency_id"=>Currency::where("name","DKK")->first()->id,
                "phone_code"=>"298",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"France",
                "code"=>"fr",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"33",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Gabon",
                "code"=>"ga",
                "currency_id"=>Currency::where("name","XAF")->first()->id,
                "phone_code"=>"241",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Grenada",
                "code"=>"gd",
                "currency_id"=>Currency::where("name","XCD")->first()->id,
                "phone_code"=>"1473",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Georgia",
                "code"=>"ge",
                "currency_id"=>Currency::where("name","GEL")->first()->id,
                "phone_code"=>"995",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"French Guiana",
                "code"=>"gf",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"594",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Ghana",
                "code"=>"gh",
                "currency_id"=>Currency::where("name","GHS")->first()->id,
                "phone_code"=>"233",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Gibraltar",
                "code"=>"gi",
                "currency_id"=>Currency::where("name","GIP")->first()->id,
                "phone_code"=>"350",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Guernsey",
                "code"=>"gg",
                "currency_id"=>Currency::where("name","GBP")->first()->id,
                "phone_code"=>"44",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Greenland",
                "code"=>"gl",
                "currency_id"=>Currency::where("name","DKK")->first()->id,
                "phone_code"=>"299",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Gambia",
                "code"=>"gm",
                "currency_id"=>Currency::where("name","GMD")->first()->id,
                "phone_code"=>"220",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Guinea",
                "code"=>"gn",
                "currency_id"=>Currency::where("name","GNF")->first()->id,
                "phone_code"=>"224",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Guadeloupe",
                "code"=>"gp",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"590",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Equatorial Guinea",
                "code"=>"gq",
                "currency_id"=>Currency::where("name","XAF")->first()->id,
                "phone_code"=>"240",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Greece",
                "code"=>"gr",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"30",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"South Georgia and the South Sandwich Islands",
                "code"=>"gs",
                "currency_id"=>Currency::where("name","GBP")->first()->id,
                "phone_code"=>"500",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Guatemala",
                "code"=>"gt",
                "currency_id"=>Currency::where("name","GTQ")->first()->id,
                "phone_code"=>"502",
                "vat_label"=>"NIT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Guam",
                "code"=>"gu",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"1671",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Guinea-Bissau",
                "code"=>"gw",
                "currency_id"=>Currency::where("name","XOF")->first()->id,
                "phone_code"=>"245",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Guyana",
                "code"=>"gy",
                "currency_id"=>Currency::where("name","GYD")->first()->id,
                "phone_code"=>"592",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Hong Kong",
                "code"=>"hk",
                "currency_id"=>Currency::where("name","HKD")->first()->id,
                "phone_code"=>"852",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Heard Island and McDonald Islands",
                "code"=>"hm",
                "currency_id"=>Currency::where("name","AUD")->first()->id,
                "phone_code"=>"672",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Honduras",
                "code"=>"hn",
                "currency_id"=>Currency::where("name","HNL")->first()->id,
                "phone_code"=>"504",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Croatia",
                "code"=>"hr",
                "currency_id"=>Currency::where("name","HRK")->first()->id,
                "phone_code"=>"385",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Haiti",
                "code"=>"ht",
                "currency_id"=>Currency::where("name","HTG")->first()->id,
                "phone_code"=>"509",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Hungary",
                "code"=>"hu",
                "currency_id"=>Currency::where("name","HUF")->first()->id,
                "phone_code"=>"36",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Indonesia",
                "code"=>"id",
                "currency_id"=>Currency::where("name","IDR")->first()->id,
                "phone_code"=>"62",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Ireland",
                "code"=>"ie",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"353",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Israel",
                "code"=>"il",
                "currency_id"=>Currency::where("name","ILS")->first()->id,
                "phone_code"=>"972",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Isle of Man",
                "code"=>"im",
                "currency_id"=>Currency::where("name","GBP")->first()->id,
                "phone_code"=>"44",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"India",
                "code"=>"in",
                "currency_id"=>Currency::where("name","INR")->first()->id,
                "phone_code"=>"91",
                "vat_label"=>"GSTIN",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"British Indian Ocean Territory",
                "code"=>"io",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"246",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Iraq",
                "code"=>"iq",
                "currency_id"=>Currency::where("name","IQD")->first()->id,
                "phone_code"=>"964",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Iran",
                "code"=>"ir",
                "currency_id"=>Currency::where("name","IRR")->first()->id,
                "phone_code"=>"98",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Iceland",
                "code"=>"is",
                "currency_id"=>Currency::where("name","ISK")->first()->id,
                "phone_code"=>"354",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Italy",
                "code"=>"it",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"39",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Jersey",
                "code"=>"je",
                "currency_id"=>Currency::where("name","GBP")->first()->id,
                "phone_code"=>"44",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Jamaica",
                "code"=>"jm",
                "currency_id"=>Currency::where("name","JMD")->first()->id,
                "phone_code"=>"1876",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Jordan",
                "code"=>"jo",
                "currency_id"=>Currency::where("name","JOD")->first()->id,
                "phone_code"=>"962",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Japan",
                "code"=>"jp",
                "currency_id"=>Currency::where("name","JPY")->first()->id,
                "phone_code"=>"81",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Kenya",
                "code"=>"ke",
                "currency_id"=>Currency::where("name","KES")->first()->id,
                "phone_code"=>"254",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Kyrgyzstan",
                "code"=>"kg",
                "currency_id"=>Currency::where("name","KGS")->first()->id,
                "phone_code"=>"996",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Cambodia",
                "code"=>"kh",
                "currency_id"=>Currency::where("name","KHR")->first()->id,
                "phone_code"=>"855",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Kiribati",
                "code"=>"ki",
                "currency_id"=>Currency::where("name","AUD")->first()->id,
                "phone_code"=>"686",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Comoros",
                "code"=>"km",
                "currency_id"=>Currency::where("name","KMF")->first()->id,
                "phone_code"=>"269",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Saint Kitts and Nevis",
                "code"=>"kn",
                "currency_id"=>Currency::where("name","XCD")->first()->id,
                "phone_code"=>"1869",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"North Korea",
                "code"=>"kp",
                "currency_id"=>Currency::where("name","KPW")->first()->id,
                "phone_code"=>"850",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"South Korea",
                "code"=>"kr",
                "currency_id"=>Currency::where("name","KRW")->first()->id,
                "phone_code"=>"82",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Kuwait",
                "code"=>"kw",
                "currency_id"=>Currency::where("name","KWD")->first()->id,
                "phone_code"=>"965",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Cayman Islands",
                "code"=>"ky",
                "currency_id"=>Currency::where("name","KYD")->first()->id,
                "phone_code"=>"1345",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Kazakhstan",
                "code"=>"kz",
                "currency_id"=>Currency::where("name","KZT")->first()->id,
                "phone_code"=>"7",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Laos",
                "code"=>"la",
                "currency_id"=>Currency::where("name","LAK")->first()->id,
                "phone_code"=>"856",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Lebanon",
                "code"=>"lb",
                "currency_id"=>Currency::where("name","LBP")->first()->id,
                "phone_code"=>"961",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Saint Lucia",
                "code"=>"lc",
                "currency_id"=>Currency::where("name","XCD")->first()->id,
                "phone_code"=>"1758",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Liechtenstein",
                "code"=>"li",
                "currency_id"=>Currency::where("name","CHF")->first()->id,
                "phone_code"=>"423",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Sri Lanka",
                "code"=>"lk",
                "currency_id"=>Currency::where("name","LKR")->first()->id,
                "phone_code"=>"94",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Liberia",
                "code"=>"lr",
                "currency_id"=>Currency::where("name","LRD")->first()->id,
                "phone_code"=>"231",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Lesotho",
                "code"=>"ls",
                "currency_id"=>Currency::where("name","LSL")->first()->id,
                "phone_code"=>"266",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Lithuania",
                "code"=>"lt",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"370",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Luxembourg",
                "code"=>"lu",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"352",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Latvia",
                "code"=>"lv",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"371",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Libya",
                "code"=>"ly",
                "currency_id"=>Currency::where("name","LYD")->first()->id,
                "phone_code"=>"218",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Morocco",
                "code"=>"ma",
                "currency_id"=>Currency::where("name","MAD")->first()->id,
                "phone_code"=>"212",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Monaco",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "code"=>"mc",
                "phone_code"=>"377",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Moldova",
                "code"=>"md",
                "currency_id"=>Currency::where("name","MDL")->first()->id,
                "phone_code"=>"373",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Montenegro",
                "code"=>"me",
                "currency_id"=>Currency::where("name","LYD")->first()->id,
                "phone_code"=>"382",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Saint Martin (French part)",
                "code"=>"mf",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"590",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Madagascar",
                "code"=>"mg",
                "currency_id"=>Currency::where("name","MGA")->first()->id,
                "phone_code"=>"261",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Marshall Islands",
                "code"=>"mh",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"692",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Macedonia, the former Yugoslav Republic of",
                "code"=>"mk",
                "currency_id"=>Currency::where("name","MKD")->first()->id,
                "phone_code"=>"389",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Mali",
                "code"=>"ml",
                "currency_id"=>Currency::where("name","XOF")->first()->id,
                "phone_code"=>"223",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Myanmar",
                "code"=>"mm",
                "currency_id"=>Currency::where("name","MMK")->first()->id,
                "phone_code"=>"95",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Mongolia",
                "code"=>"mn",
                "currency_id"=>Currency::where("name","MNT")->first()->id,
                "phone_code"=>"976",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Macau",
                "code"=>"mo",
                "currency_id"=>Currency::where("name","MOP")->first()->id,
                "phone_code"=>"853",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Northern Mariana Islands",
                "code"=>"mp",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"1670",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Martinique",
                "code"=>"mq",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"596",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Mauritania",
                "code"=>"mr",
                "currency_id"=>Currency::where("name","MRU")->first()->id,
                "phone_code"=>"222",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Montserrat",
                "code"=>"ms",
                "currency_id"=>Currency::where("name","XCD")->first()->id,
                "phone_code"=>"1664",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Malta",
                "code"=>"mt",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"356",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Mauritius",
                "code"=>"mu",
                "currency_id"=>Currency::where("name","MUR")->first()->id,
                "phone_code"=>"230",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Maldives",
                "code"=>"mv",
                "currency_id"=>Currency::where("name","MVR")->first()->id,
                "phone_code"=>"960",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Malawi",
                "code"=>"mw",
                "currency_id"=>Currency::where("name","MWK")->first()->id,
                "phone_code"=>"265",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Mexico",
                "code"=>"mx",
                "currency_id"=>Currency::where("name","MXN")->first()->id,
                "phone_code"=>"52",
                "vat_label"=>"RFC",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Malaysia",
                "code"=>"my",
                "currency_id"=>Currency::where("name","MYR")->first()->id,
                "phone_code"=>"60",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Mozambique",
                "code"=>"mz",
                "currency_id"=>Currency::where("name","MZN")->first()->id,
                "phone_code"=>"258",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Namibia",
                "code"=>"na",
                "currency_id"=>Currency::where("name","NAD")->first()->id,
                "phone_code"=>"264",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"New Caledonia",
                "code"=>"nc",
                "currency_id"=>Currency::where("name","XPF")->first()->id,
                "phone_code"=>"687",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Niger",
                "code"=>"ne",
                "currency_id"=>Currency::where("name","XOF")->first()->id,
                "phone_code"=>"227",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Norfolk Island",
                "code"=>"nf",
                "currency_id"=>Currency::where("name","AUD")->first()->id,
                "phone_code"=>"672",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Nigeria",
                "code"=>"ng",
                "currency_id"=>Currency::where("name","NGN")->first()->id,
                "phone_code"=>"234",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Nicaragua",
                "code"=>"ni",
                "currency_id"=>Currency::where("name","NIO")->first()->id,
                "phone_code"=>"505",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Netherlands",
                "code"=>"nl",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"31",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Norway",
                "code"=>"no",
                "currency_id"=>Currency::where("name","NOK")->first()->id,
                "phone_code"=>"47",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Nepal",
                "code"=>"np",
                "currency_id"=>Currency::where("name","NPR")->first()->id,
                "phone_code"=>"977",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Nauru",
                "code"=>"nr",
                "currency_id"=>Currency::where("name","AUD")->first()->id,
                "phone_code"=>"674",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Niue",
                "code"=>"nu",
                "currency_id"=>Currency::where("name","NZD")->first()->id,
                "phone_code"=>"683",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"New Zealand",
                "code"=>"nz",
                "currency_id"=>Currency::where("name","NZD")->first()->id,
                "phone_code"=>"64",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Oman",
                "code"=>"om",
                "currency_id"=>Currency::where("name","OMR")->first()->id,
                "phone_code"=>"968",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Panama",
                "code"=>"pa",
                "currency_id"=>Currency::where("name","PAB")->first()->id,
                "phone_code"=>"507",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Peru",
                "code"=>"pe",
                "currency_id"=>Currency::where("name","PEN")->first()->id,
                "phone_code"=>"51",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"French Polynesia",
                "code"=>"pf",
                "currency_id"=>Currency::where("name","XPF")->first()->id,
                "phone_code"=>"689",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Papua New Guinea",
                "code"=>"pg",
                "currency_id"=>Currency::where("name","PGK")->first()->id,
                "phone_code"=>"675",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Philippines",
                "code"=>"ph",
                "currency_id"=>Currency::where("name","PHP")->first()->id,
                "phone_code"=>"63",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Pakistan",
                "code"=>"pk",
                "currency_id"=>Currency::where("name","PKR")->first()->id,
                "phone_code"=>"92",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Poland",
                "code"=>"pl",
                "currency_id"=>Currency::where("name","PLN")->first()->id,
                "phone_code"=>"48",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Saint Pierre and Miquelon",
                "code"=>"pm",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"508",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Pitcairn Islands",
                "code"=>"pn",
                "currency_id"=>Currency::where("name","NZD")->first()->id,
                "phone_code"=>"64",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Puerto Rico",
                "code"=>"pr",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"1939",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"State of Palestine",
                "code"=>"ps",
                "currency_id"=>Currency::where("name","ILS")->first()->id,
                "phone_code"=>"970",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Portugal",
                "code"=>"pt",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"351",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Palau",
                "code"=>"pw",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"680",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Paraguay",
                "code"=>"py",
                "currency_id"=>Currency::where("name","PYG")->first()->id,
                "phone_code"=>"595",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Qatar",
                "code"=>"qa",
                "currency_id"=>Currency::where("name","QAR")->first()->id,
                "phone_code"=>"974",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Réunion",
                "code"=>"re",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"262",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Romania",
                "code"=>"ro",
                "currency_id"=>Currency::where("name","RON")->first()->id,
                "phone_code"=>"40",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Serbia",
                "code"=>"rs",
                "currency_id"=>Currency::where("name","RSD")->first()->id,
                "phone_code"=>"381",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Russian Federation",
                "code"=>"ru",
                "currency_id"=>Currency::where("name","RUB")->first()->id,
                "phone_code"=>"7",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Rwanda",
                "code"=>"rw",
                "currency_id"=>Currency::where("name","RWF")->first()->id,
                "phone_code"=>"250",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Saudi Arabia",
                "code"=>"sa",
                "currency_id"=>Currency::where("name","SAR")->first()->id,
                "phone_code"=>"966",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Solomon Islands",
                "code"=>"sb",
                "currency_id"=>Currency::where("name","SBD")->first()->id,
                "phone_code"=>"677",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Seychelles",
                "code"=>"sc",
                "currency_id"=>Currency::where("name","SCR")->first()->id,
                "phone_code"=>"248",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Sudan",
                "code"=>"sd",
                "currency_id"=>Currency::where("name","SDG")->first()->id,
                "phone_code"=>"249",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Sweden",
                "code"=>"se",
                "currency_id"=>Currency::where("name","SEK")->first()->id,
                "phone_code"=>"46",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Singapore",
                "code"=>"sg",
                "currency_id"=>Currency::where("name","SGD")->first()->id,
                "phone_code"=>"65",
                "vat_label"=>"GST No.",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Saint Helena, Ascension and Tristan da Cunha",
                "code"=>"sh",
                "currency_id"=>Currency::where("name","SHP")->first()->id,
                "phone_code"=>"290",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Slovenia",
                "code"=>"si",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"386",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Svalbard and Jan Mayen",
                "code"=>"sj",
                "currency_id"=>Currency::where("name","NOK")->first()->id,
                "phone_code"=>"47",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Slovakia",
                "code"=>"sk",
                "currency_id"=>Currency::where("name","SKK")->first()->id,
                "phone_code"=>"421",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Sierra Leone",
                "code"=>"sl",
                "currency_id"=>Currency::where("name","SLL")->first()->id,
                "phone_code"=>"232",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"San Marino",
                "code"=>"sm",
                "currency_id"=>Currency::where("name","ITL")->first()->id,
                "phone_code"=>"378",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Senegal",
                "code"=>"sn",
                "currency_id"=>Currency::where("name","XOF")->first()->id,
                "phone_code"=>"221",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Somalia",
                "code"=>"so",
                "currency_id"=>Currency::where("name","SOD")->first()->id,
                "phone_code"=>"252",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Suriname",
                "code"=>"sr",
                "currency_id"=>Currency::where("name","SRD")->first()->id,
                "phone_code"=>"597",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"South Sudan",
                "code"=>"ss",
                "currency_id"=>Currency::where("name","SSP")->first()->id,
                "phone_code"=>"211",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"São Tomé and Príncipe",
                "code"=>"st",
                "currency_id"=>Currency::where("name","STD")->first()->id,
                "phone_code"=>"239",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"El Salvador",
                "code"=>"sv",
                "currency_id"=>Currency::where("name","SVC")->first()->id,
                "phone_code"=>"503",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Sint Maarten (Dutch part)",
                "code"=>"sx",
                "currency_id"=>Currency::where("name","ANG")->first()->id,
                "phone_code"=>"1721",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Syria",
                "code"=>"sy",
                "currency_id"=>Currency::where("name","SYP")->first()->id,
                "phone_code"=>"963",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Swaziland",
                "code"=>"sz",
                "currency_id"=>Currency::where("name","SZL")->first()->id,
                "phone_code"=>"268",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Turks and Caicos Islands",
                "code"=>"tc",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"1649",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Chad",
                "code"=>"td",
                "currency_id"=>Currency::where("name","XAF")->first()->id,
                "phone_code"=>"235",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"French Southern Territories",
                "code"=>"tf",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"262",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Togo",
                "code"=>"tg",
                "currency_id"=>Currency::where("name","XOF")->first()->id,
                "phone_code"=>"228",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Thailand",
                "code"=>"th",
                "currency_id"=>Currency::where("name","THB")->first()->id,
                "phone_code"=>"66",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Tajikistan",
                "code"=>"tj",
                "currency_id"=>Currency::where("name","TJS")->first()->id,
                "phone_code"=>"992",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Tokelau",
                "code"=>"tk",
                "currency_id"=>Currency::where("name","NZD")->first()->id,
                "phone_code"=>"690",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Turkmenistan",
                "code"=>"tm",
                "currency_id"=>Currency::where("name","TMT")->first()->id,
                "phone_code"=>"993",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Tunisia",
                "code"=>"tn",
                "currency_id"=>Currency::where("name","TND")->first()->id,
                "phone_code"=>"216",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Tonga",
                "code"=>"to",
                "currency_id"=>Currency::where("name","TOP")->first()->id,
                "phone_code"=>"676",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Timor-Leste",
                "code"=>"tl",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"670",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Turkey",
                "code"=>"tr",
                "currency_id"=>Currency::where("name","TRY")->first()->id,
                "phone_code"=>"90",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Trinidad and Tobago",
                "code"=>"tt",
                "currency_id"=>Currency::where("name","TTD")->first()->id,
                "phone_code"=>"1868",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Tuvalu",
                "code"=>"tv",
                "currency_id"=>Currency::where("name","AUD")->first()->id,
                "phone_code"=>"688",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Taiwan",
                "code"=>"tw",
                "currency_id"=>Currency::where("name","TWD")->first()->id,
                "phone_code"=>"886",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Tanzania",
                "code"=>"tz",
                "currency_id"=>Currency::where("name","TZS")->first()->id,
                "phone_code"=>"255",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Ukraine",
                "code"=>"ua",
                "currency_id"=>Currency::where("name","UAH")->first()->id,
                "phone_code"=>"380",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Uganda",
                "code"=>"ug",
                "currency_id"=>Currency::where("name","UGX")->first()->id,
                "phone_code"=>"256",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"United Kingdom",
                "code"=>"gb",
                "currency_id"=>Currency::where("name","GBP")->first()->id,
                "phone_code"=>"44",
                "vat_label"=>"VAT",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"USA Minor Outlying Islands",
                "code"=>"um",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"699",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"United States",
                "code"=>"us",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"1",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Uruguay",
                "code"=>"uy",
                "currency_id"=>Currency::where("name","UYU")->first()->id,
                "phone_code"=>"598",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Uzbekistan",
                "code"=>"uz",
                "currency_id"=>Currency::where("name","UZS")->first()->id,
                "phone_code"=>"998",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Holy See (Vatican City State)",
                "code"=>"va",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"379",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Saint Vincent and the Grenadines",
                "code"=>"vc",
                "currency_id"=>Currency::where("name","XCD")->first()->id,
                "phone_code"=>"1784",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Venezuela",
                "code"=>"ve",
                "currency_id"=>Currency::where("name","VEF")->first()->id,
                "phone_code"=>"58",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Virgin Islands (British)",
                "code"=>"vg",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"1284",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Virgin Islands (USA)",
                "code"=>"vi",
                "currency_id"=>Currency::where("name","USD")->first()->id,
                "phone_code"=>"1340",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Vietnam",
                "code"=>"vn",
                "currency_id"=>Currency::where("name","VND")->first()->id,
                "phone_code"=>"84",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Vanuatu",
                "code"=>"vu",
                "currency_id"=>Currency::where("name","VUV")->first()->id,
                "phone_code"=>"678",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Wallis and Futuna",
                "code"=>"wf",
                "currency_id"=>Currency::where("name","XPF")->first()->id,
                "phone_code"=>"681",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Samoa",
                "code"=>"ws",
                "currency_id"=>Currency::where("name","WST")->first()->id,
                "phone_code"=>"685",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Yemen",
                "code"=>"ye",
                "currency_id"=>Currency::where("name","YER")->first()->id,
                "phone_code"=>"967",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Mayotte",
                "code"=>"yt",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"262",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"South Africa",
                "code"=>"za",
                "currency_id"=>Currency::where("name","ZAR")->first()->id,
                "phone_code"=>"27",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Zambia",
                "code"=>"zm",
                "currency_id"=>Currency::where("name","ZMW")->first()->id,
                "phone_code"=>"260",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Zimbabwe",
                "code"=>"zw",
                "currency_id"=>Currency::where("name","ZWL")->first()->id,
                "phone_code"=>"263",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"Kosovo",
                "code"=>"xk",
                "currency_id"=>Currency::where("name","EUR")->first()->id,
                "phone_code"=>"383",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
        ];
        return $country;
    }
}
