<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ResCurrency as Currency;

class ResCurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->CreateCurrency();
    }

    public Function CreateCurrency()
    {
        $currency_data = $this->CurrencyData();
        foreach ($currency_data as $currency) {
            Currency::create($currency);
        }
    }

    public function CurrencyData()
    {
        $currency = [
            [
                "name"=>"USD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"before",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"VEF",
                "symbol"=>"Bs.F",
                "rounding"=>"0.0001",
                "position"=>"after",
                "currency_unit_label"=>"Bolivar",
                "currency_subunit_label"=>"Centimos",
                "decimal_places"=>"4",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"CAD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"CHF",
                "symbol"=>"CHF",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Franc",
                "currency_subunit_label"=>"Centimes",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BRL",
                "symbol"=>"R$",
                "rounding"=>"0.01",
                "position"=>"after",
                "position"=>"before",
                "currency_unit_label"=>"Real",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"CNY",
                "symbol"=>"¥",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Yuan",
                "currency_subunit_label"=>"Fen",
                "position"=>"before",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"COP",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "position"=>"before",
                "currency_unit_label"=>"Peso",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"CZK",
                "symbol"=>"Kč",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Koruna",
                "currency_subunit_label"=>"Halers",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"DKK",
                "symbol"=>"kr",
                "rounding"=>"0.01",
                "position"=>"before",
                "position"=>"after",
                "currency_unit_label"=>"Krone",
                "currency_subunit_label"=>"Ore",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"HUF",
                "symbol"=>"Ft",
                "rounding"=>"1.00",
                "position"=>"after",
                "currency_unit_label"=>"Forint",
                "currency_subunit_label"=>"Filler",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"IDR",
                "symbol"=>"Rp",
                "rounding"=>"0.01",
                "position"=>"before",
                "position"=>"after",
                "currency_unit_label"=>"Rupiah",
                "currency_subunit_label"=>"Sen",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"LVL",
                "symbol"=>"Ls",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Lats",
                "currency_subunit_label"=>"Santims",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"NOK",
                "symbol"=>"kr",
                "rounding"=>"0.01",
                "position"=>"before",
                "position"=>"after",
                "currency_unit_label"=>"Krone",
                "currency_subunit_label"=>"Ore",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"XPF",
                "symbol"=>"XPF",
                "rounding"=>"1.00",
                "position"=>"after",
                "currency_unit_label"=>"Franc",
                "currency_subunit_label"=>"Centimes",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"PAB",
                "symbol"=>"B/.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Balboa",
                "currency_subunit_label"=>"Centesimo",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"PLN",
                "symbol"=>"zł",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Zloty",
                "currency_subunit_label"=>"Groszy",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SEK",
                "symbol"=>"kr",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Krona",
                "currency_subunit_label"=>"Ore",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ARS",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"before",
                "position"=>"after",
                "currency_unit_label"=>"Peso",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"INR",
                "symbol"=>"₹",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rupees",
                "currency_subunit_label"=>"Paise",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"AUD",
                "symbol"=>"$",
                "position"=>"before",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"UAH",
                "symbol"=>"₴",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Hryvnia",
                "currency_subunit_label"=>"Kopiyka",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"VND",
                "symbol"=>"₫",
                "rounding"=>"1.00",
                "position"=>"after",
                "currency_unit_label"=>"Dong",
                "currency_subunit_label"=>"Xu",
                "decimal_places"=>"0",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"HKD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"JPY",
                "symbol"=>"¥",
                "rounding"=>"1.00",
                "position"=>"after",
                "position"=>"before",
                "currency_unit_label"=>"Yen",
                "currency_subunit_label"=>"Cen",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BGN",
                "symbol"=>"лв",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Lev",
                "currency_subunit_label"=>"Stotinki",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"LTL",
                "symbol"=>"Lt",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Litas",
                "currency_subunit_label"=>"Centas",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"RON",
                "symbol"=>"lei",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Leu",
                "currency_subunit_label"=>"Bani",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"HRK",
                "symbol"=>"kn",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Kuna",
                "currency_subunit_label"=>"Lipa",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"RUB",
                "symbol"=>"руб",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Ruble",
                "currency_subunit_label"=>"Kopek",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"TRY",
                "symbol"=>"₺",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Lira",
                "currency_subunit_label"=>"Kurus",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"KRW",
                "symbol"=>"₩",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Won",
                "currency_subunit_label"=>"Chon",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MXN",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "position"=>"before",
                "currency_unit_label"=>"Pesos",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MYR",
                "symbol"=>"RM",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Ringgit",
                "currency_subunit_label"=>"Sen",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"NZD",
                "symbol"=>"$",
                "position"=>"before",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"PHP",
                "symbol"=>"Php",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Peso",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SGD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ZAR",
                "symbol"=>"R",
                "rounding"=>"0.01",
                "position"=>"before",
                "position"=>"after",
                "currency_unit_label"=>"Rand",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"CRC",
                "rounding"=>"0.01",
                "symbol"=>"¢",
                "position"=>"after",
                "currency_unit_label"=>"Colon",
                "currency_subunit_label"=>"Centimos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MUR",
                "symbol"=>"Rs",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rupee",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"XOF",
                "symbol"=>"CFA",
                "rounding"=>"1",
                "position"=>"after",
                "currency_unit_label"=>"Franc",
                "currency_subunit_label"=>"Centimes",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"XAF",
                "symbol"=>"FCFA",
                "rounding"=>"1",
                "position"=>"after",
                "currency_unit_label"=>"Franc",
                "currency_subunit_label"=>"Centimes",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"UGX",
                "symbol"=>"USh",
                "rounding"=>"1",
                "position"=>"after",
                "currency_unit_label"=>"Shilling",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"HNL",
                "symbol"=>"L",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Lempira",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"CLP",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Peso",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"UYU",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Peso",
                "currency_subunit_label"=>"Centesimos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"AFN",
                "symbol"=>"Afs",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Afghani",
                "currency_subunit_label"=>"Puls",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"AOA",
                "symbol"=>"Kz",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Kwanza",
                "currency_subunit_label"=>"Centimos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"XCD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"AMD",
                "symbol"=>"դր.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dram",
                "currency_subunit_label"=>"Luma",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"AWG",
                "symbol"=>"Afl.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Guilder",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"AZN",
                "symbol"=>"m",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Manat",
                "currency_subunit_label"=>"Qapik",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BSD",
                "symbol"=>"B$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BHD",
                "symbol"=>"BD",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dinar",
                "currency_subunit_label"=>"Fils",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BDT",
                "symbol"=>"৳",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Taka",
                "currency_subunit_label"=>"Paisa",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BBD",
                "symbol"=>"Bds$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BYR",
                "symbol"=>"BR",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Ruble BYR",
                "currency_subunit_label"=>"Kapeyka",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BYN",
                "symbol"=>"Br",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rubles",
                "currency_subunit_label"=>"Kopeks",            
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BZD",
                "symbol"=>"BZ$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BMD",
                "symbol"=>"BD$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BTN",
                "symbol"=>"Nu.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Ngultrum",
                "currency_subunit_label"=>"Chhertum",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BOB",
                "symbol"=>"Bs.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Boliviano",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BAM",
                "symbol"=>"KM",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Mark",
                "currency_subunit_label"=>"Fening",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BWP",
                "symbol"=>"P",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Pula",
                "currency_subunit_label"=>"Thebe",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BIF",
                "symbol"=>"FBu",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Franc",
                "currency_subunit_label"=>"Centime",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"KHR",
                "symbol"=>"៛",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Riel",
                "currency_subunit_label"=>"Sen",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"KYD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"KMF",
                "symbol"=>"CF",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Franc",
                "currency_subunit_label"=>"Centime",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"CDF",
                "symbol"=>"Fr",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Franc",
                "currency_subunit_label"=>"Centime",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"CUP",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Peso",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ANG",
                "symbol"=>"ƒ",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Guilder",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"CYP",
                "symbol"=>"£",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Euros",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"DJF",
                "symbol"=>"Fdj",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Franc",
                "currency_subunit_label"=>"Centime",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"DOP",
                "symbol"=>"RD$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Pesos",
                "currency_subunit_label"=>"Centavos",
                "position"=>"before",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ECS",
                "symbol"=>"S/.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Sucre",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"EGP",
                "symbol"=>"E£",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Pound",
                "currency_subunit_label"=>"Piastres",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SVC",
                "symbol"=>"¢",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Colones",
                "currency_subunit_label"=>"Centavo",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ERN",
                "symbol"=>"Nfk",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Nakfa",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ETB",
                "symbol"=>"Br",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Birr",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"FKP",
                "symbol"=>"£",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Pound",
                "currency_subunit_label"=>"Penny",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"FJD",
                "symbol"=>"FJ$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"GEL",
                "symbol"=>"ლ",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Lari",
                "currency_subunit_label"=>"Tetri",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"GIP",
                "symbol"=>"£",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Pound",
                "currency_subunit_label"=>"Penny",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"QTQ",
                "symbol"=>"Q",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Quetzales",
                "currency_subunit_label"=>"Centavo",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"GNF",
                "symbol"=>"FG",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Franc",
                "currency_subunit_label"=>"Centime",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"GYD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"HTG",
                "symbol"=>"G",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Gourde",
                "currency_subunit_label"=>"Centime",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ISK",
                "symbol"=>"kr",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Krona",
                "currency_subunit_label"=>"Aurar",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"IRR",
                "symbol"=>"﷼",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dinar",
                "currency_subunit_label"=>"Fils",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"IQD",
                "symbol"=>" ع.د",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dinar",
                "currency_subunit_label"=>"Fils",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ILS",
                "symbol"=>"₪",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Shekel",
                "currency_subunit_label"=>"Agorot",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"JMD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"JOD",
                "symbol"=>" د.ا ",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dinar",
                "currency_subunit_label"=>"Fils",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"KZT",
                "symbol"=>"лв",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Tenge",
                "currency_subunit_label"=>"Tiin",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"KES",
                "symbol"=>"KSh",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Shilling",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"KWD",
                "symbol"=>" د.ك ",
                "rounding"=>"0.001",
                "position"=>"after",
                "currency_unit_label"=>"Dinar",
                "currency_subunit_label"=>"Fils",
                "decimal_places"=>"3",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"KGS",
                "symbol"=>"лв",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Som",
                "currency_subunit_label"=>"Tyiyn",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"LAK",
                "symbol"=>"₭",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Kip",
                "currency_subunit_label"=>"Att",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"LBP",
                "symbol"=>"ل.ل",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Pound",
                "currency_subunit_label"=>"Piastres",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"LSL",
                "symbol"=>"L",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Loti",
                "currency_subunit_label"=>"Sente",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"LRD",
                "symbol"=>"L$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"LYD",
                "symbol"=>" ل.د ",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dinar",
                "currency_subunit_label"=>"Centimes",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MOP",
                "symbol"=>"MOP$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Pataca",
                "currency_subunit_label"=>"Sin",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MKD",
                "symbol"=>"ден",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Denar",
                "currency_subunit_label"=>"Deni",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MGA",
                "symbol"=>"Ar",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Ariary",
                "currency_subunit_label"=>"Iraimbilanja",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MWK",
                "symbol"=>"MK",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Kwacha",
                "currency_subunit_label"=>"Tambala",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MVR",
                "symbol"=>".ރ",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rufiyaa",
                "currency_subunit_label"=>"Laari",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MRO",
                "symbol"=>"UM",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Ouguiya",
                "currency_subunit_label"=>"Khoums",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MRU",
                "symbol"=>"UM",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Ouguiya",
                "currency_subunit_label"=>"Khoums",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MDL",
                "symbol"=>"L",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Leu",
                "currency_subunit_label"=>"Ban",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MNT",
                "symbol"=>"₮",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Tugrik",
                "currency_subunit_label"=>"Mongo",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MAD",
                "symbol"=>"DH",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dirham",
                "currency_subunit_label"=>"Centimes",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"BND",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"DZD",
                "symbol"=>"DA",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dinar",
                "currency_subunit_label"=>"Centimes",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"GHS",
                "symbol"=>"GH¢",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Cedi",
                "currency_subunit_label"=>"Pesewas",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"GMD",
                "symbol"=>"D",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dalasi",
                "currency_subunit_label"=>"Butut",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ZRZ",
                "symbol"=>"Ƶ",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Zaire",
                "currency_subunit_label"=>"Likuta",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MZN",
                "symbol"=>"MT",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Metical",
                "currency_subunit_label"=>"Centavo",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"MMK",
                "symbol"=>"K",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Kyat",
                "currency_subunit_label"=>"Pya",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"NAD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"NPR",
                "symbol"=>"₨",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rupee",
                "currency_subunit_label"=>"Paisa",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ALL",
                "symbol"=>"L",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Lek",
                "currency_subunit_label"=>"Qindarke",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"NIO",
                "symbol"=>"C$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Cordoba",
                "currency_subunit_label"=>"Centavos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"NGN",
                "symbol"=>"₦",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Naira",
                "currency_subunit_label"=>"Kobo",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"KPW",
                "symbol"=>"₩",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Won",
                "currency_subunit_label"=>"Chon",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ZWL",
                "symbol"=>"Z$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ZMW",
                "symbol"=>"ZK",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Kwacha",
                "currency_subunit_label"=>"Ngwee",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"YER",
                "symbol"=>"﷼",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rial",
                "currency_subunit_label"=>"Fils",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"EUR",
                "symbol"=>"€",
                "rounding"=>"0.01",
                "currency_unit_label"=>"Euros",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"VUV",
                "symbol"=>"VT",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Vatu",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"UZS",
                "symbol"=>"лв",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Som",
                "currency_subunit_label"=>"Tiyin",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"AED",
                "symbol"=>"د.إ",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dirham",
                "currency_subunit_label"=>"Fils",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"UAG",
                "symbol"=>"₴",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Hryvnia",
                "currency_subunit_label"=>"Kopiyka",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"TMT",
                "symbol"=>"T",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Manat",
                "currency_subunit_label"=>"Tenge",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"TND",
                "symbol"=>"DT",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dinar",
                "currency_subunit_label"=>"Millimes",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"TTD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"TOP",
                "symbol"=>"T$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Paanga",
                "currency_subunit_label"=>"Seniti",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"THB",
                "symbol"=>"฿",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Baht",
                "currency_subunit_label"=>"Satang",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"TZS",
                "symbol"=>"TSh",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Shilling",
                "currency_subunit_label"=>"Senti",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"TJS",
                "symbol"=>"TJS",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Somoni",
                "currency_subunit_label"=>"Diram",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"TWD",
                "symbol"=>"NT$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SYP",
                "symbol"=>"£",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Pound",
                "currency_subunit_label"=>"Piastrp",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SZL",
                "symbol"=>"E",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Lilangeni",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SRD",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SDG",
                "symbol"=>"ج.س.",
                "rounding"=>"0.01",
                "position"=>"after",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"LKR",
                "symbol"=>"Rs",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rupee",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SSP",
                "symbol"=>"£",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Pounds",
                "currency_subunit_label"=>"Piasters",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"GBP",
                "symbol"=>"£",
                "rounding"=>"0.01",
                "position"=>"before",
                "position"=>"after",
                "currency_unit_label"=>"Sterling",
                "currency_subunit_label"=>"Penny",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SOD",
                "symbol"=>"Sh.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Shillings",
                "currency_subunit_label"=>"Senti",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SBD",
                "symbol"=>"SI$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dollars",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SLL",
                "symbol"=>"Le",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Leone",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SCR",
                "symbol"=>"SR",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rupee",
                "currency_subunit_label"=>"Cents",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"RSD",
                "symbol"=>"din.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dinar",
                "currency_subunit_label"=>"Para",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SAR",
                "symbol"=>"SR",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Riyal",
                "currency_subunit_label"=>"Halala",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"STD",
                "symbol"=>"Db",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dobra",
                "currency_subunit_label"=>"Centimo",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"ITL",
                "symbol"=>"₤",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Lira",
                "currency_subunit_label"=>"Centesimo",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"WST",
                "symbol"=>"WS$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Tala",
                "currency_subunit_label"=>"Sene",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SHP",
                "symbol"=>"£",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Pound",
                "currency_subunit_label"=>"Penny",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"RWF",
                "symbol"=>"RF",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Franc",
                "currency_subunit_label"=>"Santime",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"RUR",
                "symbol"=>"R",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Ruble",
                "currency_subunit_label"=>"Kopek",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"QAR",
                "symbol"=>"QR",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rial",
                "currency_subunit_label"=>"Dirham",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"PLZ",
                "symbol"=>"zł",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Zloty",
                "currency_subunit_label"=>"Grosz",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"PEN",
                "symbol"=>"S/",
                "rounding"=>"0.01",
                "position"=>"after",
                "position"=>"before",
                "currency_unit_label"=>"Inti",
                "currency_subunit_label"=>"Centimes",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"PYG",
                "symbol"=>"₲",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Guarani",
                "currency_subunit_label"=>"Centimos",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"PGK",
                "symbol"=>"K",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Kina",
                "currency_subunit_label"=>"Toea",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"PKR",
                "symbol"=>"Rs.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rupee",
                "currency_subunit_label"=>"Paisa",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"OMR",
                "symbol"=>"ر.ع.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Rial",
                "currency_subunit_label"=>"Baisa",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"CVE",
                "symbol"=>"$",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Escudo",
                "currency_subunit_label"=>"Centavo",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"SKK",
                "symbol"=>"Sk",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Koruna",
                "currency_subunit_label"=>"Halier",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"YUM",
                "symbol"=>"дин.",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Dinar",
                "currency_subunit_label"=>"Para",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                "name"=>"GTQ",
                "symbol"=>"Q",
                "rounding"=>"0.01",
                "position"=>"after",
                "currency_unit_label"=>"Quetzal",
                "currency_subunit_label"=>"Centavo",
                "decimal_places"=>"2",
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],

        ];
        return $currency;
    }
}