<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ResLang as language;

class ReslangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->CreateLang();
    }

    public Function CreateLang()
    {
        $lang_data = $this->LangData();
        foreach ($lang_data as $lang) {
            language::create($lang);
        }
    }

    public function LangData()
    {
        return [
            [
                'name' => 'English (US)',
                'code' => 'en_US',
                'iso_code' => 'en_US',
                'url_code' => 'en_US',
                'direction' => 'ltr',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%I:%M:%S',
                'week_start' => 'Sunday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Amharic / አምሃርኛ',
                'code' => 'am_ET',
                'iso_code' => 'am_ET',
                'url_code' => 'am_ET',
                'direction' => 'ltr',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%I:%M:%S',
                'week_start' => 'Sunday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Arabic / الْعَرَبيّة',
                'code' => 'ar_IL',
                'iso_code' => 'ar_IL',
                'url_code' => 'ar_IL',
                'direction' => 'rtl',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Sunday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Arabic (Syria) / الْعَرَبيّة',
                'code' => 'ar_SY',
                'iso_code' => 'ar_SY',
                'url_code' => 'ar_SY',
                'direction' => 'rtl',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Sunday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Basque / Euskara',
                'code' => 'eu_ES',
                'iso_code' => 'eu_ES',
                'url_code' => 'eu_ES',
                'direction' => 'ltr',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%I:%M:%S',
                'week_start' => 'Sunday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bengali / বাংলা',
                'code' => 'bn_BD',
                'iso_code' => 'bn_BD',
                'url_code' => 'bn_BD',
                'direction' => 'ltr',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%I:%M:%S',
                'week_start' => 'Sunday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bosnian / bosanski jezik',
                'code' => 'bs_BA',
                'iso_code' => 'bs_BA',
                'url_code' => 'bs_BA',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bulgarian / български език',
                'code' => 'bg_BG',
                'iso_code' => 'bg_BG',
                'url_code' => 'bg_BG',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Catalan / Català',
                'code' => 'ca_ES',
                'iso_code' => 'ca_ES',
                'url_code' => 'ca_ES',
                'direction' => 'ltr',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%I:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chinese (Simplified) / 简体中文',
                'code' => 'zh_CN',
                'iso_code' => 'zh_CN',
                'url_code' => 'zh_CN',
                'direction' => 'ltr',
                'date_format' => '%Y-%m-%d',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chinese (HK)',
                'code' => 'zh_HK',
                'iso_code' => 'zh_HK',
                'url_code' => 'zh_HK',
                'direction' => 'ltr',
                'date_format' => '%Y-%m-%d',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Chinese (Traditional) / 正體字',
                'code' => 'zh_TW',
                'iso_code' => 'zh_TW',
                'url_code' => 'zh_TW',
                'direction' => 'ltr',
                'date_format' => '%Y-%m-%d',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Croatian / Hrvatski',
                'code' => 'hr_HR',
                'iso_code' => 'hr_HR',
                'url_code' => 'hr_HR',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Czech / česky',
                'code' => 'cs_CZ',
                'iso_code' => 'cs_CZ',
                'url_code' => 'cs_CZ',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Danish / Dansk',
                'code' => 'da_DK',
                'iso_code' => 'da_DK',
                'url_code' => 'da_DK',
                'direction' => 'ltr',
                'date_format' => '%d-%m-%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dutch (BE) / Nederlands (BE)',
                'code' => 'nl_BE',
                'iso_code' => 'nl_BE',
                'url_code' => 'nl_BE',
                'direction' => 'ltr',
                'date_format' => '%d-%m-%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dutch / Nederlands',
                'code' => 'nl_NL',
                'iso_code' => 'nl_NL',
                'url_code' => 'nl_NL',
                'direction' => 'ltr',
                'date_format' => '%d-%m-%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'English (AU) / English (Australia)',
                'code' => 'en_AU',
                'iso_code' => 'en_AU',
                'url_code' => 'en_AU',
                'direction' => 'ltr',
                'date_format' => '%d-%m-%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'English (CA) / English (Canada)',
                'code' => 'en_CA',
                'iso_code' => 'en_CA',
                'url_code' => 'en_CA',
                'direction' => 'ltr',
                'date_format' => '%Y-%m-%d',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'English (UK)',
                'code' => 'en_GB',
                'iso_code' => 'en_GB',
                'url_code' => 'en_GB',
                'direction' => 'ltr',
                'date_format' => '%Y-%m-%d',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Estonian / Eesti keel',
                'code' => 'et_EE',
                'iso_code' => 'et_EE',
                'url_code' => 'et_EE',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Finnish / Suomi',
                'code' => 'fi_FI',
                'iso_code' => 'fi_FI',
                'url_code' => 'fi_FI',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Filipino',
                'code' => 'fil_PH',
                'iso_code' => 'fil_PH',
                'url_code' => 'fil_PH',
                'direction' => 'ltr',
                'date_format' => '%Y-%m-%d',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'French (BE) / Français (BE)',
                'code' => 'fr_BE',
                'iso_code' => 'fr_BE',
                'url_code' => 'fr_BE',
                'direction' => 'ltr',
                'date_format' => '%d-%m-%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),   
            ],
            [
                'name' => 'French (CA) / Français (Canada)',
                'code' => 'fr_CA',
                'iso_code' => 'fr_CA',
                'url_code' => 'fr_CA',
                'direction' => 'ltr',
                'date_format' => '%Y-%m-%d',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'French (CH) / Français (CH)',
                'code' => 'fr_CH',
                'iso_code' => 'fr_CH',
                'url_code' => 'fr_CH',
                'direction' => 'ltr',
                'date_format' => '%Y-%m-%d',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'French (FR) / Français (France)',
                'code' => 'fr_FR',
                'iso_code' => 'fr_FR',
                'url_code' => 'fr_FR',
                'direction' => 'ltr',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Galician / Galego',
                'code' => 'gl_ES',
                'iso_code' => 'gl_ES',
                'url_code' => 'gl_ES',
                'direction' => 'ltr',
                'date_format' => '%d-%m-%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Georgian / ქართული ენა',
                'code' => 'ka_GE',
                'iso_code' => 'ka_GE',
                'url_code' => 'ka_GE',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'German / Deutsch',
                'code' => 'de_DE',
                'iso_code' => 'de_DE',
                'url_code' => 'de_DE',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'German (CH) / Deutsch (CH)',
                'code' => 'de_CH',
                'iso_code' => 'de_CH',
                'url_code' => 'de_CH',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Greek / Ελληνικά',
                'code' => 'el_GR',
                'iso_code' => 'el_GR',
                'url_code' => 'el_GR',
                'direction' => 'ltr',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Gujarati / ગુજરાતી',
                'code' => 'gu_IN',
                'iso_code' => 'gu_IN',
                'url_code' => 'gu_IN',
                'direction' => 'ltr',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Hebrew / עִבְרִי',
                'code' => 'he_IL',
                'iso_code' => 'he_IL',
                'url_code' => 'he_IL',
                'direction' => 'rtl',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Sunday',
                'grouping' => '[4,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Hindi / हिंदी',
                'code' => 'hi_IN',
                'iso_code' => 'hi_IN',
                'url_code' => 'hi_IN',
                'direction' => 'ltr',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Sunday',
                'grouping' => '[4,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Hungarian / Magyar',
                'code' => 'hu_HU',
                'iso_code' => 'hu_HU',
                'url_code' => 'hu_HU',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Indonesian / Bahasa Indonesia',
                'code' => 'id_ID',
                'iso_code' => 'id_ID',
                'url_code' => 'id_ID',
                'direction' => 'ltr',
                'date_format' => '%d-%m-%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Italian / Italiano',
                'code' => 'it_IT',
                'iso_code' => 'it_IT',
                'url_code' => 'it_IT',
                'direction' => 'ltr',
                'date_format' => '%d/%m/%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Japanese / 日本語',
                'code' => 'ja_JP',
                'iso_code' => 'ja_JP',
                'url_code' => 'ja_JP',
                'direction' => 'ltr',
                'date_format' => '%Y/%m/%d',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Lithuanian / Lietuvių kalba',
                'code' => 'lt_LT',
                'iso_code' => 'lt_LT',
                'url_code' => 'lt_LT',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Luxembourgish',
                'code' => 'lb_LU',
                'iso_code' => 'lb_LU',
                'url_code' => 'lb_LU',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Macedonian / македонски јазик',
                'code' =>'mk_MK',
                'iso_code' =>'mk_MK',
                'url_code' =>'mk_MK',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Mongolian / монгол',
                'code' =>'mn_MN',
                'iso_code' =>'mn_MN',
                'url_code' =>'mn_MN',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Burmese / ဗမာစာ',
                'code' =>'my_MM',
                'iso_code' =>'my_MM',
                'url_code' =>'my_MM',
                'direction' => 'ltr',
                'date_format' => '%d-%m-%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Norwegian Bokmål',
                'code' => 'nb_NO',
                'iso_code' => 'nb_NO',
                'url_code' => 'nb_NO',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Russian / русский язык',
                'code' => 'ru_RU',
                'iso_code' => 'ru_RU',
                'url_code' => 'ru_RU',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Serbian (Cyrillic) / српски',
                'code' =>'sr_RS',
                'iso_code' =>'sr_RS',
                'url_code' =>'sr_RS',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Serbian (Latin) / srpski',
                'code' =>'sr_RS@latin',
                'iso_code' =>'sr_RS@latin',
                'url_code' =>'sr_RS@latin',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Slovak / Slovenský jazyk',
                'code' =>'sk_SK',
                'iso_code' =>'sk_SK',
                'url_code' =>'sk_SK',
                'direction' => 'ltr',
                'date_format' => '%d.%m.%Y',
                'time_format' => '%H:%M:%S',
                'week_start' => 'Monday',
                'grouping' => '[3,0]',
                'decimal_point' => '.',
                'thousands_sep' => ',',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            

        ];
//         INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (2, 'Amharic / አምሃርኛ', 'am_ET', 'am_ET', 'am_ET', null, 'ltr', '%d/%m/%Y', '%I:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (34, 'Hebrew / עִבְרִי', 'he_IL', 'he', 'he', null, 'rtl', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (35, 'Hindi / हिंदी', 'hi_IN', 'hi', 'hi', null, 'ltr', '%A %d %b %Y', '%I:%M:%S', '7', '[]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (36, 'Hungarian / Magyar', 'hu_HU', 'hu', 'hu', null, 'ltr', '%Y-%m-%d', '%H.%M.%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (37, 'Indonesian / Bahasa Indonesia', 'id_ID', 'id', 'id', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (38, 'Italian / Italiano', 'it_IT', 'it', 'it', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (39, 'Japanese / 日本語', 'ja_JP', 'ja', 'ja', null, 'ltr', '%Y年%m月%d日', '%H時%M分%S秒', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (40, 'Kabyle / Taqbaylit', 'kab_DZ', 'kab', 'kab', null, 'ltr', '%m/%d/%Y', '%I:%M:%S %p', '6', '[]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (41, 'Khmer / ភាសាខ្មែរ', 'km_KH', 'km', 'km', null, 'ltr', '%d %B %Y', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (42, 'Korean (KP) / 한국어 (KP)', 'ko_KP', 'ko_KP', 'ko_KP', null, 'ltr', '%m/%d/%Y', '%I:%M:%S %p', '1', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (43, 'Korean (KR) / 한국어 (KR)', 'ko_KR', 'ko_KR', 'ko_KR', null, 'ltr', '%Y년 %m월 %d일', '%H시 %M분 %S초', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (44, 'Lao / ພາສາລາວ', 'lo_LA', 'lo', 'lo', null, 'ltr', '%d/%m/y', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (45, 'Latvian / latviešu valoda', 'lv_LV', 'lv', 'lv', null, 'ltr', '%Y.%m.%d.', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (52, 'Persian / فارس', 'fa_IR', 'fa', 'fa', null, 'rtl', '%Y/%m/%d', '%H:%M:%S', '6', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (53, 'Polish / Język polski', 'pl_PL', 'pl', 'pl', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[]', ',', null,'2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (54, 'Portuguese (AO) / Português (AO)', 'pt_AO', 'pt_AO', 'pt_AO', null, 'ltr', '%d-%m-%Y', '%H:%M:%S', '1', '[]', ',', null,'2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (55, 'Portuguese (BR) / Português (BR)', 'pt_BR', 'pt_BR', 'pt_BR', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (56, 'Portuguese / Português', 'pt_PT', 'pt', 'pt', null, 'ltr', '%d-%m-%Y', '%H:%M:%S', '1', '[]', ',', null,'2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (57, 'Romanian / română', 'ro_RO', 'ro', 'ro', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (64, 'Spanish (BO) / Español (BO)', 'es_BO', 'es_BO', 'es_BO', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (65, 'Spanish (CL) / Español (CL)', 'es_CL', 'es_CL', 'es_CL', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (66, 'Spanish (CO) / Español (CO)', 'es_CO', 'es_CO', 'es_CO', null, 'ltr', '%d-%m-%Y', '%H:%M:%S', '7', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (67, 'Spanish (CR) / Español (CR)', 'es_CR', 'es_CR', 'es_CR', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (68, 'Spanish (DO) / Español (DO)', 'es_DO', 'es_DO', 'es_DO', null, 'ltr', '%d/%m/%Y', '%I:%M:%S %p', '1', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (69, 'Spanish (EC) / Español (EC)', 'es_EC', 'es_EC', 'es_EC', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (70, 'Spanish (GT) / Español (GT)', 'es_GT', 'es_GT', 'es_GT', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (71, 'Spanish (MX) / Español (MX)', 'es_MX', 'es_MX', 'es_MX', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (72, 'Spanish (PA) / Español (PA)', 'es_PA', 'es_PA', 'es_PA', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (73, 'Spanish (PE) / Español (PE)', 'es_PE', 'es_PE', 'es_PE', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (74, 'Spanish (PY) / Español (PY)', 'es_PY', 'es_PY', 'es_PY', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (75, 'Spanish (UY) / Español (UY)', 'es_UY', 'es_UY', 'es_UY', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (76, 'Spanish (VE) / Español (VE)', 'es_VE', 'es_VE', 'es_VE', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (77, 'Spanish / Español', 'es_ES', 'es', 'es', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (78, 'Swedish / Svenska', 'sv_SE', 'sv', 'sv', null, 'ltr', '%Y-%m-%d', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (80, 'Thai / ภาษาไทย', 'th_TH', 'th', 'th', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (3, 'Arabic / الْعَرَبيّة', 'ar_001', 'ar', 'ar', null, 'rtl', '%d %b, %Y', '%I:%M:%S', '6', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (4, 'Arabic (Syria) / الْعَرَبيّة', 'ar_SY', 'ar_SY', 'ar_SY', null, 'rtl', '%d %b, %Y', '%I:%M:%S', '6', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (5, 'Basque / Euskara', 'eu_ES', 'eu_ES', 'eu_ES', null, 'ltr', '%a, %Y.eko %bren %da', '%H:%M:%S', '1', '[]', ',', null,'2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (6, 'Bengali / বাংলা', 'bn_IN', 'bn_IN', 'bn_IN', null, 'ltr', '%A %d %b %Y', '%I:%M:%S', '1', '[]', ',', null,'2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (7, 'Bosnian / bosanski jezik', 'bs_BA', 'bs', 'bs', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '7', '[]', ',', null,'2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (8, 'Bulgarian / български език', 'bg_BG', 'bg', 'bg', null, 'ltr', '%d.%m.%Y', '%H,%M,%S', '1', '[3,0]', ',', null,'2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (9, 'Catalan / Català', 'ca_ES', 'ca_ES', 'ca_ES', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (10, 'Chinese (Simplified) / 简体中文', 'zh_CN', 'zh_CN', 'zh_CN', null, 'ltr', '%Y年%m月%d日', '%H时%M分%S秒', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (11, 'Chinese (HK)', 'zh_HK', 'zh_HK', 'zh_HK', null, 'ltr', '%Y年%m月%d日 %A', '%I時%M分%S秒', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (12, 'Chinese (Traditional) / 正體字', 'zh_TW', 'zh_TW', 'zh_TW', null, 'ltr', '%Y年%m月%d日', '%H時%M分%S秒', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (13, 'Croatian / hrvatski jezik', 'hr_HR', 'hr', 'hr', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (14, 'Czech / Čeština', 'cs_CZ', 'cs_CZ', 'cs_CZ', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (15, 'Danish / Dansk', 'da_DK', 'da_DK', 'da_DK', null, 'ltr', '%d-%m-%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (16, 'Dutch (BE) / Nederlands (BE)', 'nl_BE', 'nl_BE', 'nl_BE', null, 'ltr', '%d-%m-%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (17, 'Dutch / Nederlands', 'nl_NL', 'nl', 'nl', null, 'ltr', '%d-%m-%Y', '%H:%M:%S', '1', '[]', ',', null,'2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (18, 'English (AU)', 'en_AU', 'en_AU', 'en_AU', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (19, 'English (CA)', 'en_CA', 'en_CA', 'en_CA', null, 'ltr', '%Y-%m-%d', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (20, 'English (UK)', 'en_GB', 'en_GB', 'en_GB', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (21, 'Estonian / Eesti keel', 'et_EE', 'et', 'et', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (22, 'Finnish / Suomi', 'fi_FI', 'fi', 'fi', null, 'ltr', '%d.%m.%Y', '%H.%M.%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (23, 'Filipino', 'fil_PH', 'fil', 'fil', null, 'ltr', '%m/%d/%y', '%H:%M:%S', '1', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (24, 'French (BE) / Français (BE)', 'fr_BE', 'fr_BE', 'fr_BE', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (25, 'French (CA) / Français (CA)', 'fr_CA', 'fr_CA', 'fr_CA', null, 'ltr', '%Y-%m-%d', '%H:%M:%S', '7', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (26, 'French (CH) / Français (CH)', 'fr_CH', 'fr_CH', 'fr_CH', null, 'ltr', '%d. %m. %Y', '%H:%M:%S', '1', '[3,0]', '.', '''','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (27, 'French / Français', 'fr_FR', 'fr', 'fr', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (28, 'Galician / Galego', 'gl_ES', 'gl', 'gl', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[]', ',', null,'2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (29, 'Georgian / ქართული ენა', 'ka_GE', 'ka', 'ka', null, 'ltr', '%m/%d/%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (30, 'German / Deutsch', 'de_DE', 'de', 'de', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (31, 'German (CH) / Deutsch (CH)', 'de_CH', 'de_CH', 'de_CH', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[3,3]', '.', '''','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (32, 'Greek / Ελληνικά', 'el_GR', 'el_GR', 'el_GR', null, 'ltr', '%d/%m/%Y', '%I:%M:%S %p', '1', '[]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (33, 'Gujarati / ગુજરાતી', 'gu_IN', 'gu', 'gu', null, 'ltr', '%A %d %b %Y', '%I:%M:%S', '7', '[]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (46, 'Lithuanian / Lietuvių kalba', 'lt_LT', 'lt', 'lt', null, 'ltr', '%Y-%m-%d', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (47, 'Luxembourgish', 'lb_LU', 'lb', 'lb', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (48, 'Macedonian / македонски јазик', 'mk_MK', 'mk', 'mk', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (49, 'Mongolian / монгол', 'mn_MN', 'mn', 'mn', null, 'ltr', '%Y-%m-%d', '%H:%M:%S', '7', '[3,0]', '.', '''','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (50, 'Burmese / ဗမာစာ', 'my_MM', 'my', 'my', null, 'ltr', '%Y %b %d %A', '%I:%M:%S %p', '7', '[3,3]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (51, 'Norwegian Bokmål / Norsk bokmål', 'nb_NO', 'nb_NO', 'nb_NO', null, 'ltr', '%d. %b %Y', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (58, 'Russian / русский язык', 'ru_RU', 'ru', 'ru', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (59, 'Serbian (Cyrillic) / српски', 'sr_RS', 'sr_RS', 'sr_RS', null, 'ltr', '%d.%m.%Y.', '%H:%M:%S', '7', '[]', ',', null,'2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (60, 'Serbian (Latin) / srpski', 'sr@latin', 'sr@latin', 'sr@latin', null, 'ltr', '%m/%d/%Y', '%I:%M:%S %p', '7', '[]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (61, 'Slovak / Slovenský jazyk', 'sk_SK', 'sk', 'sk', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (62, 'Slovenian / slovenščina', 'sl_SI', 'sl', 'sl', null, 'ltr', '%d. %m. %Y', '%H:%M:%S', '1', '[]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (63, 'Spanish (AR) / Español (AR)', 'es_AR', 'es_AR', 'es_AR', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '7', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (1, 'English (US)', 'en_US', 'en', 'en', true, 'ltr', '%m/%d/%Y', '%H:%M:%S', '7', '[3,0]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (81, 'Turkish / Türkçe', 'tr_TR', 'tr', 'tr', null, 'ltr', '%d-%m-%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (82, 'Ukrainian / українська', 'uk_UA', 'uk', 'uk', null, 'ltr', '%d.%m.%Y', '%H:%M:%S', '1', '[3,0]', ',', ' ','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (83, 'Vietlang_namese / Tiếng Việt', 'vi_VN', 'vi', 'vi', null, 'ltr', '%d/%m/%Y', '%H:%M:%S', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (84, 'Albanian / Shqip', 'sq_AL', 'sq', 'sq', null, 'ltr', '%Y-%b-%d', '%I.%M.%S.', '1', '[3,0]', ',', '.','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
// INSERT INTO res_lang (id, lang_name, code, iso_code, url_code, active, direction, date_format, time_format, week_start, grouping, decimal_point, thousands_sep, created_at, updated_at) VALUES (85, 'Telugu / తెలుగు', 'te_IN', 'te', 'te', null, 'ltr', '%B %d %A %Y', '%p%I.%M.%S', '7', '[]', '.', ',','2020-02-28 13:51:24.093028','2020-03-23 12:06:23.539487');
    }

}