<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice {{$invoice->invoice_no}}</title>
    <style>
        .customer {
            padding-left: 500px;
        }
        footer { position: fixed; bottom: 130px; left: 0px; right: 0px; height: 50px; }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <table style="border:0;" width="100%">
        <tr>
            <td>
                <img src="{{ public_path('/images/logo/segargroup.png')}}" width="120px" height="120px">
            <td width=100%>
                <ul style="list-style-type:none;">
                    <li><span class="text"><b>Segar Kumala Indonesia</b></span></li>
                    <li><span class="text">Jln. Sutomo Simpang.Seikera No. 25D Kota medan </span></li>
                    <li><span class="text">kec.medan Timur, Sumatera Utara, Indonesia</span></li>
                    <li><span class="text">(+62-21) 4608000 | skfresh@gmail.com</span></li>
                </ul>
            </td>
        </tr>
    </table>
    <hr style="border: 1px solid;">
    <div class="customer">
        <ul style="list-style-type:none;" class="pull-right">
            <li><span class="text">{{$invoice->customer->parent_id}} , {{$invoice->customer->name}}</span></li>
            <li><span class="text">{{$invoice->customer->address}}</span></li>
            <li><span class="text">{{$invoice->customer->city}}, {{$invoice->customer->street}} </span></li>
            <li><span class="text">{{$invoice->customer->phone}}</span></li>
            <li><span class="text">{{$invoice->customer->email}}</span></li>
        </ul>
    </div>
    <table>
    <tr>
        <td colspan="2" style="font-size:30px;">
            <b>Invoice No {{$invoice->invoice_no}}</b>
        </td>
    </tr>
    <tr>
        <td class="mt-3">
            <b>Invoice Date :</b>
        </td>
        <td class="mt-3">
            <b>Due Date :</b>
        </td>
    </tr>
    <tr>
        <td>
            {{$invoice->invoice_date}}
        </td>
        <td>
            {{$invoice->due_date}}
        </td>
    </tr>
    </table>
    <table class="table mt-3">
        <thead>
            <tr>
            <th scope="col">No</th>
            <th scope="col">Product Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoice->products as $product)
                <tr>
                    <td scope="row">{{$loop->iteration}}
                    <td id="product" class="table-name">{{$product->name}}</td>
                    <td class="table-price">Rp. {{number_format($product->price)}}</td>
                    <td class="table-qty">{{$product->qty}}</td>
                    <td class="table-total">Rp. {{number_format($product->qty * $product->price)}}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td class="table-empty" colspan="3"></td>
                <td class="table-label">Sub Total</td>
                <td class="table-amount">Rp. {{number_format($invoice->sub_total)}}</td>
            </tr>
            <tr>
                <td class="table-empty" colspan="3" style="border:0;"></td>
                <td class="table-label">Discount</td>
                <td class="table-amount">Rp. {{number_format($invoice->discount)}}</td>
            </tr>
            <tr>
                <td class="table-empty" colspan="3" style="border:0;"></td>
                <td class="table-label">Grand Total</td>
                <td class="table-amount">Rp. {{number_format($invoice->grand_total)}}</td>
            </tr>
        </tfoot>
    </table>
    <footer>
        <div>
        Memo: {{$invoice->title}}
        <p class="text-secondary mb-0">Note: This Invoice is automatically generated by the system so it doesn't require a signature from the company</P>
        </div>
        <div class="text-center">
            <div class="row">
                <div class="col-sm-12">
                <hr style="border: 1px solid black">
                <div class="mt-0">
                <b>{{ config('app.name') }}</b>
                </div>
                <hr style="border: 1px solid ">
                </div>
            </div>
        </div>
    </footer>
</body>
</html>