@extends('reports.layouts.report')
@section('title')
<title>{{$orders->status}} | {{$orders->order_no}}</title>
@endsection
@section('content')
    <div class="customer">
        <ul style="list-style-type:none;" class="pull-right">
            <li><span class="text">{{$orders->partner->parent_id}} , {{$orders->partner->partner_name}}</span></li>
            <li><span class="text">{{$orders->partner->street}}</span></li>
            <li><span class="text">{{$orders->partner->street2}} , {{$orders->partner->city}} </span></li>
            <li><span class="text">{{$orders->partner->phone}}</span></li>
            <li><span class="text">{{$orders->partner->email}}</span></li>
        </ul>
    </div>
    <table>
    <tr> 
        @if ($orders->status == "Quotation")
            <td colspan="2" style="font-size:30px;">
                <b>Quotation No {{$orders->order_no}}</b>
            </td>
        @endif
        @if ($orders->status == "PO")
            <td colspan="2" style="font-size:30px;">
                <b>Order No {{$orders->order_no}}</b>
            </td>
        @endif
    </tr>
    <tr>
        <td class="mt-3">
            <b>order Date :</b>
        </td>
        <td class="mt-3">
            <b>Merchandise :</b>
        </td>
    </tr>
    <tr>
        <td>
            {{$orders->order_date}}
        </td>
        <td>
            {{$orders->sales->employee_name}}
        </td>
    </tr>
    </table>
    <table class="table mt-3">
        <thead>
            <tr>
            <th scope="col">No</th>
            <th scope="col">Product Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders->products as $data)
                <tr>
                    <td scope="row">{{$loop->iteration}}
                    <td id="product" class="table-name">{{$data->product->name}}</td>
                    <td class="table-price">Rp. {{ number_format($data->price)}}</td>
                    <td class="table-qty">{{$data->qty}}</td>
                    <td class="table-total text-right">Rp. {{ number_format($data->qty * $data->price)}}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td class="table-empty" colspan="3"></td>
                <td class="table-label">Sub Total</td>
                <td class="table-amount">Rp. {{number_format($orders->sub_total)}}</td>
            </tr>
            <tr>
                <td class="table-empty" colspan="3" style="border:0;"></td>
                <td class="table-label">Discount</td>
                <td class="table-amount">Rp. {{number_format($orders->discount)}}</td>
            </tr>
            <tr>
                <td class="table-empty" colspan="3" style="border:0;"></td>
                <td class="table-label">Grand Total</td>
                <td class="table-amount">Rp. {{number_format($orders->grand_total)}}</td>
            </tr>
        </tfoot>
    </table>
    <footer>
        <div>
        Memo: {{$orders->title}}
        <p class="text-secondary mb-0">Note: This order is automatically generated by the system so it doesn't require a signature from the company</P>
        </div>
        <div class="text-center">
            <div class="row">
                <div class="col-sm-12">
                <hr style="border: 1px solid black">
                <div class="mt-0">
                <b>{{ config('app.name') }}</b>
                </div>
                <hr style="border: 1px solid ">
                </div>
            </div>
        </div>
    </footer>
@endsection
